#!/bin/sh

plat=`uname`

if [ $plat == 'Darwin' ]; then
        export FFLAGS="-ff2c"
fi

cd pyinstaller
rm -rf dist/*
pyinstaller pyEventAnalysis.spec
cp Info.plist dist/pyEventAnalysis.app/Contents/
cd ..

