#!/bin/sh

plat=`uname`



ver=$(<version)
read -d '' info1 <<-"EOF"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleIdentifier</key>
	<string>pyEventAnalysis</string>
	<key>CFBundleShortVersionString</key>
	<string>
EOF
read -d '' info2 <<-"EOF"
	</string>
	<key>CFBundleExecutable</key>
	<string>MacOS/pyEventAnalysis</string>
	<key>CFBundleName</key>
	<string>pyEventAnalysis</string>
	<key>NSHighResolutionCapable</key>
	<string>True</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleDisplayName</key>
	<string>pyEventAnalysis</string>
	<key>CFBundleIconFile</key>
	<string>icon-windowed.icns</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>LSBackgroundOnly</key>
	<true/>
</dict>
</plist>
EOF
infoplist="$info1$ver$info2"

cd pyinstaller
rm -rf dist/* build/*
pyinstaller pyEventAnalysis.spec

if [ $plat == 'Darwin' ]; then
	echo ${infoplist}>dist/pyEventAnalysis.app/Contents/Info.plist
	cd dist
	hdiutil create ./pyEventAnalysis-${ver}.dmg -srcfolder pyEventAnalysis.app -ov
	mv ./pyEventAnalysis-${ver}.dmg ../../dist/
else
	cd dist
	zip pyEventAnalysis-${ver}.zip pyEventAnalysis.exe
	mv ./pyEventAnalysis-${ver}.zip ../../dist/
fi

cd ../..

