#! /usr/bin/env python
import sys
import mosaicgui.mosaicGUI

def main():
	return mosaicgui.mosaicGUI.main()

if __name__ == '__main__':
	if sys.platform.startswith('win'):
		multiprocessing.freeze_support()
	main()