#! /usr/bin/env python
import sys
import mosaicgui.mosaicGUI as mosaicgui
from PyQt4 import QtCore
# from PyQt4.QtCore import Qt
from PyQt4 import QtGui


def main():
	app = QtGui.QApplication(sys.argv)
	dmw = mosaicgui.qtAnalysisGUI()
	dmw.show()
	dmw.raise_()

	# cleanup processing
	app.connect(app, QtCore.SIGNAL("aboutToQuit()"), dmw.OnQuit)
	
	sys.exit(app.exec_())

if __name__ == '__main__':
	if sys.platform.startswith('win'):
		multiprocessing.freeze_support()
	main()