import os
import time

"""
	Interface class to write and query metadata 

	Author: Arvind Balijepalli
	Created:	3/1/2014

	ChangeLog:
		3/1/14		AB	Initial version
"""
from abc import ABCMeta, abstractmethod

class InsufficientArgumentsError(Exception):
	pass

class metaMDIO(object):
	"""
		This class provides the skeleton for storing metadata
		generated by algorithms. It also provides an interface to query metadata, for example in a 
		SQL database.
	"""
	__metaclass__=ABCMeta

	def __init__(self):
		self.pid=os.getpid()

	def initDB(self, **kwargs):
		"""
			Initialize the database.

			Args: 
			The arguments	passed to init change based on the method of file IO selected, in addition to 
			the common args below:
				dbPath		directory to store the MD database ('<full path to data directory>')
				colNames 	list of text names for the columns in the tables
				colNames_t	list of data types for each column. 
		"""
		# start by setting all passed keyword arguments as class attributes
		for (k,v) in kwargs.iteritems():
			setattr(self, k, v)

		if not hasattr(self, 'dbPath'):
			raise InsufficientArgumentsError("Missing arguments: 'dbPath' must be supplied to initialize {0}".format(type(self).__name__))
		if not hasattr(self, 'colNames'):
			raise InsufficientArgumentsError("Missing arguments: 'colNames' must be supplied to initialize {0}".format(type(self).__name__))
		if not hasattr(self, 'colNames_t'):
			raise InsufficientArgumentsError("Missing arguments: 'colNames_t' must be supplied to initialize {0}".format(type(self).__name__))

		self._initdb(**kwargs)

	def openDB(self, dbname, **kwargs):
		self._opendb(dbname, **kwargs)

	@abstractmethod
	def _opendb(self, dbname, **kwargs):
		pass

	@abstractmethod
	def _initdb(self, **kwargs):
		pass

	@abstractmethod
	def closeDB(self):
		pass

	@abstractmethod
	def writeRecord(self, data, table=None):
		"""
			Write data to a specified table. By default table 
			is None. In this case sub-classes should fall back 
			to writing data to a default table.
		"""
		pass

	@abstractmethod
	def writeSettings(self, settingsstring):
		"""
			Write the settings JSON object into a settings database/table.
		"""
		pass

	@abstractmethod
	def _colnames(self):
		pass

	@abstractmethod
	def queryDB(self, query):
		pass

	@property 
	def dbColumnNames(self):
		return self._colnames()

	def _generateRecordKey(self):
		return float(time.time()+self.pid)

