# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsWindow.ui'
#
# Created: Sat Aug  9 17:51:54 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName(_fromUtf8("SettingsWindow"))
        SettingsWindow.setEnabled(True)
        SettingsWindow.resize(400, 679)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsWindow.sizePolicy().hasHeightForWidth())
        SettingsWindow.setSizePolicy(sizePolicy)
        SettingsWindow.setMinimumSize(QtCore.QSize(400, 650))
        SettingsWindow.setMaximumSize(QtCore.QSize(400, 679))
        self.centralwidget = QtGui.QWidget(SettingsWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.dataSettingsGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.dataSettingsGroupBox.setObjectName(_fromUtf8("dataSettingsGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dataSettingsGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.dataSettingsGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.datPathLineEdit = QtGui.QLineEdit(self.dataSettingsGroupBox)
        self.datPathLineEdit.setObjectName(_fromUtf8("datPathLineEdit"))
        self.horizontalLayout.addWidget(self.datPathLineEdit)
        self.datPathToolButton = QtGui.QToolButton(self.dataSettingsGroupBox)
        self.datPathToolButton.setObjectName(_fromUtf8("datPathToolButton"))
        self.horizontalLayout.addWidget(self.datPathToolButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.dataSettingsGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.datTypeComboBox = QtGui.QComboBox(self.dataSettingsGroupBox)
        self.datTypeComboBox.setObjectName(_fromUtf8("datTypeComboBox"))
        self.datTypeComboBox.addItem(_fromUtf8(""))
        self.datTypeComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.datTypeComboBox)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_15 = QtGui.QLabel(self.dataSettingsGroupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.qdfRfbLineEdit = QtGui.QLineEdit(self.dataSettingsGroupBox)
        self.qdfRfbLineEdit.setEnabled(True)
        self.qdfRfbLineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.qdfRfbLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.qdfRfbLineEdit.setPlaceholderText(_fromUtf8(""))
        self.qdfRfbLineEdit.setObjectName(_fromUtf8("qdfRfbLineEdit"))
        self.horizontalLayout_2.addWidget(self.qdfRfbLineEdit)
        self.label_16 = QtGui.QLabel(self.dataSettingsGroupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_2.addWidget(self.label_16)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_18 = QtGui.QLabel(self.dataSettingsGroupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_3.addWidget(self.label_18)
        self.qdfCfbLineEdit = QtGui.QLineEdit(self.dataSettingsGroupBox)
        self.qdfCfbLineEdit.setEnabled(True)
        self.qdfCfbLineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.qdfCfbLineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.qdfCfbLineEdit.setPlaceholderText(_fromUtf8(""))
        self.qdfCfbLineEdit.setObjectName(_fromUtf8("qdfCfbLineEdit"))
        self.horizontalLayout_3.addWidget(self.qdfCfbLineEdit)
        self.label_19 = QtGui.QLabel(self.dataSettingsGroupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_3.addWidget(self.label_19)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.dataSettingsGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.dcOffsetDoubleSpinBox = QtGui.QDoubleSpinBox(self.dataSettingsGroupBox)
        self.dcOffsetDoubleSpinBox.setObjectName(_fromUtf8("dcOffsetDoubleSpinBox"))
        self.horizontalLayout_5.addWidget(self.dcOffsetDoubleSpinBox)
        self.label_8 = QtGui.QLabel(self.dataSettingsGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_20 = QtGui.QLabel(self.dataSettingsGroupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_9.addWidget(self.label_20)
        self.startIndexLineEdit = QtGui.QLineEdit(self.dataSettingsGroupBox)
        self.startIndexLineEdit.setEnabled(True)
        self.startIndexLineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.startIndexLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.startIndexLineEdit.setObjectName(_fromUtf8("startIndexLineEdit"))
        self.horizontalLayout_9.addWidget(self.startIndexLineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addWidget(self.dataSettingsGroupBox)
        self.baselineGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.baselineGroupBox.setObjectName(_fromUtf8("baselineGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.baselineGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.baselineAutoCheckBox = QtGui.QCheckBox(self.baselineGroupBox)
        self.baselineAutoCheckBox.setChecked(True)
        self.baselineAutoCheckBox.setObjectName(_fromUtf8("baselineAutoCheckBox"))
        self.horizontalLayout_14.addWidget(self.baselineAutoCheckBox)
        spacerItem2 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.label_13 = QtGui.QLabel(self.baselineGroupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.baselineBlockSizeDoubleSpinBox = QtGui.QDoubleSpinBox(self.baselineGroupBox)
        self.baselineBlockSizeDoubleSpinBox.setDecimals(2)
        self.baselineBlockSizeDoubleSpinBox.setMaximum(50.0)
        self.baselineBlockSizeDoubleSpinBox.setSingleStep(0.25)
        self.baselineBlockSizeDoubleSpinBox.setProperty("value", 0.5)
        self.baselineBlockSizeDoubleSpinBox.setObjectName(_fromUtf8("baselineBlockSizeDoubleSpinBox"))
        self.horizontalLayout_12.addWidget(self.baselineBlockSizeDoubleSpinBox)
        self.label_17 = QtGui.QLabel(self.baselineGroupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.baselineGroupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.baselineMeanLineEdit = QtGui.QLineEdit(self.baselineGroupBox)
        self.baselineMeanLineEdit.setEnabled(False)
        self.baselineMeanLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.baselineMeanLineEdit.setObjectName(_fromUtf8("baselineMeanLineEdit"))
        self.horizontalLayout_7.addWidget(self.baselineMeanLineEdit)
        self.label_10 = QtGui.QLabel(self.baselineGroupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.baselineSDLineEdit = QtGui.QLineEdit(self.baselineGroupBox)
        self.baselineSDLineEdit.setEnabled(False)
        self.baselineSDLineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.baselineSDLineEdit.setObjectName(_fromUtf8("baselineSDLineEdit"))
        self.horizontalLayout_7.addWidget(self.baselineSDLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(64, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.baselineGroupBox)
        self.eventPartitionGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.eventPartitionGroupBox.setObjectName(_fromUtf8("eventPartitionGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.eventPartitionGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_7 = QtGui.QLabel(self.eventPartitionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 26))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_11.addWidget(self.label_7)
        self.partitionAlgorithmComboBox = QtGui.QComboBox(self.eventPartitionGroupBox)
        self.partitionAlgorithmComboBox.setObjectName(_fromUtf8("partitionAlgorithmComboBox"))
        self.partitionAlgorithmComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.partitionAlgorithmComboBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_14 = QtGui.QLabel(self.eventPartitionGroupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_13.addWidget(self.label_14)
        self.partitionThresholdHorizontalSlider = QtGui.QSlider(self.eventPartitionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partitionThresholdHorizontalSlider.sizePolicy().hasHeightForWidth())
        self.partitionThresholdHorizontalSlider.setSizePolicy(sizePolicy)
        self.partitionThresholdHorizontalSlider.setMinimumSize(QtCore.QSize(130, 0))
        self.partitionThresholdHorizontalSlider.setMinimum(0)
        self.partitionThresholdHorizontalSlider.setMaximum(100)
        self.partitionThresholdHorizontalSlider.setSingleStep(1)
        self.partitionThresholdHorizontalSlider.setProperty("value", 4)
        self.partitionThresholdHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.partitionThresholdHorizontalSlider.setInvertedAppearance(False)
        self.partitionThresholdHorizontalSlider.setInvertedControls(False)
        self.partitionThresholdHorizontalSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.partitionThresholdHorizontalSlider.setTickInterval(1)
        self.partitionThresholdHorizontalSlider.setObjectName(_fromUtf8("partitionThresholdHorizontalSlider"))
        self.horizontalLayout_13.addWidget(self.partitionThresholdHorizontalSlider)
        self.ThresholdDoubleSpinBox = QtGui.QDoubleSpinBox(self.eventPartitionGroupBox)
        self.ThresholdDoubleSpinBox.setMinimumSize(QtCore.QSize(60, 0))
        self.ThresholdDoubleSpinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ThresholdDoubleSpinBox.setMaximum(25.0)
        self.ThresholdDoubleSpinBox.setSingleStep(0.1)
        self.ThresholdDoubleSpinBox.setProperty("value", 4.0)
        self.ThresholdDoubleSpinBox.setObjectName(_fromUtf8("ThresholdDoubleSpinBox"))
        self.horizontalLayout_13.addWidget(self.ThresholdDoubleSpinBox)
        self.label_4 = QtGui.QLabel(self.eventPartitionGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_13.addWidget(self.label_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout_5.addWidget(self.eventPartitionGroupBox)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 26))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_16.addWidget(self.label_11)
        self.processingAlgorithmComboBox = QtGui.QComboBox(self.centralwidget)
        self.processingAlgorithmComboBox.setObjectName(_fromUtf8("processingAlgorithmComboBox"))
        self.processingAlgorithmComboBox.addItem(_fromUtf8(""))
        self.processingAlgorithmComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.processingAlgorithmComboBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.writeEventsCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.writeEventsCheckBox.setChecked(True)
        self.writeEventsCheckBox.setObjectName(_fromUtf8("writeEventsCheckBox"))
        self.verticalLayout_11.addWidget(self.writeEventsCheckBox)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.parallelCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.parallelCheckBox.setObjectName(_fromUtf8("parallelCheckBox"))
        self.horizontalLayout_6.addWidget(self.parallelCheckBox)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        self.parallelCoresSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.parallelCoresSpinBox.setEnabled(True)
        self.parallelCoresSpinBox.setProperty("value", 2)
        self.parallelCoresSpinBox.setObjectName(_fromUtf8("parallelCoresSpinBox"))
        self.horizontalLayout_8.addWidget(self.parallelCoresSpinBox)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_11)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.plotEventFitsCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.plotEventFitsCheckBox.setObjectName(_fromUtf8("plotEventFitsCheckBox"))
        self.verticalLayout_3.addWidget(self.plotEventFitsCheckBox)
        self.plotBlockDepthHistCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.plotBlockDepthHistCheckBox.setObjectName(_fromUtf8("plotBlockDepthHistCheckBox"))
        self.verticalLayout_3.addWidget(self.plotBlockDepthHistCheckBox)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.advancedModeCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.advancedModeCheckBox.setObjectName(_fromUtf8("advancedModeCheckBox"))
        self.horizontalLayout_10.addWidget(self.advancedModeCheckBox)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.startAnalysisPushButton = QtGui.QPushButton(self.centralwidget)
        self.startAnalysisPushButton.setObjectName(_fromUtf8("startAnalysisPushButton"))
        self.horizontalLayout_10.addWidget(self.startAnalysisPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuPlots = QtGui.QMenu(self.menuView)
        self.menuPlots.setObjectName(_fromUtf8("menuPlots"))
        SettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SettingsWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SettingsWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(SettingsWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionStart_Analysis = QtGui.QAction(SettingsWindow)
        self.actionStart_Analysis.setObjectName(_fromUtf8("actionStart_Analysis"))
        self.actionPyEventAnalysis_Help = QtGui.QAction(SettingsWindow)
        self.actionPyEventAnalysis_Help.setObjectName(_fromUtf8("actionPyEventAnalysis_Help"))
        self.actionEvent_Fits = QtGui.QAction(SettingsWindow)
        self.actionEvent_Fits.setObjectName(_fromUtf8("actionEvent_Fits"))
        self.actionBlockade_Depth_Histogram = QtGui.QAction(SettingsWindow)
        self.actionBlockade_Depth_Histogram.setObjectName(_fromUtf8("actionBlockade_Depth_Histogram"))
        self.actionAnalysis_Log = QtGui.QAction(SettingsWindow)
        self.actionAnalysis_Log.setObjectName(_fromUtf8("actionAnalysis_Log"))
        self.actionSettings_Window = QtGui.QAction(SettingsWindow)
        self.actionSettings_Window.setObjectName(_fromUtf8("actionSettings_Window"))
        self.actionTrajectory_Viewer = QtGui.QAction(SettingsWindow)
        self.actionTrajectory_Viewer.setObjectName(_fromUtf8("actionTrajectory_Viewer"))
        self.actionAdvanced_Settings_Mode = QtGui.QAction(SettingsWindow)
        self.actionAdvanced_Settings_Mode.setObjectName(_fromUtf8("actionAdvanced_Settings_Mode"))
        self.menuFile.addAction(self.actionStart_Analysis)
        self.menuHelp.addAction(self.actionPyEventAnalysis_Help)
        self.menuPlots.addAction(self.actionTrajectory_Viewer)
        self.menuPlots.addAction(self.actionEvent_Fits)
        self.menuPlots.addAction(self.actionBlockade_Depth_Histogram)
        self.menuView.addAction(self.actionAdvanced_Settings_Mode)
        self.menuView.addAction(self.actionAnalysis_Log)
        self.menuView.addAction(self.menuPlots.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SettingsWindow)
        QtCore.QObject.connect(self.baselineAutoCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.baselineMeanLineEdit.setDisabled)
        QtCore.QObject.connect(self.baselineAutoCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.baselineSDLineEdit.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "pyEventAnalysis", None))
        self.dataSettingsGroupBox.setTitle(_translate("SettingsWindow", "Data Settings", None))
        self.label.setText(_translate("SettingsWindow", "Path", None))
        self.datPathToolButton.setText(_translate("SettingsWindow", "...", None))
        self.label_2.setText(_translate("SettingsWindow", "File Type", None))
        self.datTypeComboBox.setItemText(0, _translate("SettingsWindow", "ABF", None))
        self.datTypeComboBox.setItemText(1, _translate("SettingsWindow", "QDF", None))
        self.label_15.setText(_translate("SettingsWindow", "Rfb", None))
        self.label_16.setText(_translate("SettingsWindow", "GΩ", None))
        self.label_18.setText(_translate("SettingsWindow", "Cfb", None))
        self.label_19.setText(_translate("SettingsWindow", "pF", None))
        self.label_5.setText(_translate("SettingsWindow", "DC Offset ", None))
        self.label_8.setText(_translate("SettingsWindow", "pA", None))
        self.label_20.setText(_translate("SettingsWindow", "Start Index", None))
        self.startIndexLineEdit.setText(_translate("SettingsWindow", "0", None))
        self.startIndexLineEdit.setPlaceholderText(_translate("SettingsWindow", "0", None))
        self.baselineGroupBox.setTitle(_translate("SettingsWindow", "Baseline Current Detection", None))
        self.baselineAutoCheckBox.setText(_translate("SettingsWindow", "Auto", None))
        self.label_13.setText(_translate("SettingsWindow", "Block Size", None))
        self.label_17.setText(_translate("SettingsWindow", "sec", None))
        self.label_9.setText(_translate("SettingsWindow", "Mean", None))
        self.baselineMeanLineEdit.setPlaceholderText(_translate("SettingsWindow", "<auto>", None))
        self.label_10.setText(_translate("SettingsWindow", "Std. Dev.", None))
        self.baselineSDLineEdit.setPlaceholderText(_translate("SettingsWindow", "<auto>", None))
        self.eventPartitionGroupBox.setTitle(_translate("SettingsWindow", "Event Partition Control", None))
        self.label_7.setText(_translate("SettingsWindow", "Algorithm", None))
        self.partitionAlgorithmComboBox.setItemText(0, _translate("SettingsWindow", "CurrentThreshold", None))
        self.label_14.setToolTip(_translate("SettingsWindow", "Ionic current threshold that controls detection of an event.", None))
        self.label_14.setText(_translate("SettingsWindow", "Threshold", None))
        self.label_4.setText(_translate("SettingsWindow", "SD", None))
        self.label_11.setText(_translate("SettingsWindow", "Event Processing Algorithm", None))
        self.processingAlgorithmComboBox.setItemText(0, _translate("SettingsWindow", "stepResponseAnalysis", None))
        self.processingAlgorithmComboBox.setItemText(1, _translate("SettingsWindow", "multiStateAnalysis", None))
        self.writeEventsCheckBox.setToolTip(_translate("SettingsWindow", "Write event time-series to disk", None))
        self.writeEventsCheckBox.setText(_translate("SettingsWindow", "Write Events to Disk", None))
        self.parallelCheckBox.setToolTip(_translate("SettingsWindow", "Use multiple processors", None))
        self.parallelCheckBox.setText(_translate("SettingsWindow", "Parallel Processing", None))
        self.label_12.setText(_translate("SettingsWindow", "Processors", None))
        self.groupBox_2.setTitle(_translate("SettingsWindow", "Plot Results", None))
        self.plotEventFitsCheckBox.setText(_translate("SettingsWindow", "Event Fits", None))
        self.plotBlockDepthHistCheckBox.setText(_translate("SettingsWindow", "Blockade Depth Histogram", None))
        self.advancedModeCheckBox.setText(_translate("SettingsWindow", "Advanced Mode", None))
        self.startAnalysisPushButton.setText(_translate("SettingsWindow", "Start Analysis", None))
        self.menuFile.setTitle(_translate("SettingsWindow", "File", None))
        self.menuHelp.setTitle(_translate("SettingsWindow", "Help", None))
        self.menuView.setTitle(_translate("SettingsWindow", "View", None))
        self.menuPlots.setTitle(_translate("SettingsWindow", "Plots", None))
        self.actionNew.setText(_translate("SettingsWindow", "New", None))
        self.actionStart_Analysis.setText(_translate("SettingsWindow", "Start Analysis", None))
        self.actionPyEventAnalysis_Help.setText(_translate("SettingsWindow", "pyEventAnalysis Help", None))
        self.actionEvent_Fits.setText(_translate("SettingsWindow", "Event Fits", None))
        self.actionBlockade_Depth_Histogram.setText(_translate("SettingsWindow", "Blockade Depth Histogram", None))
        self.actionAnalysis_Log.setText(_translate("SettingsWindow", "Analysis Log", None))
        self.actionSettings_Window.setText(_translate("SettingsWindow", "Settings Window", None))
        self.actionTrajectory_Viewer.setText(_translate("SettingsWindow", "Trajectory Viewer", None))
        self.actionAdvanced_Settings_Mode.setText(_translate("SettingsWindow", "Advanced Settings Mode", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SettingsWindow = QtGui.QMainWindow()
    ui = Ui_SettingsWindow()
    ui.setupUi(SettingsWindow)
    SettingsWindow.show()
    sys.exit(app.exec_())

