# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trajviewerui.ui'
#
# Created: Mon Mar 17 17:36:08 2014
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mplWindow(object):
    def setupUi(self, mplWindow):
        mplWindow.setObjectName(_fromUtf8("mplWindow"))
        mplWindow.resize(713, 627)
        mplWindow.setAutoFillBackground(False)
        self.centralWidget = QtGui.QWidget(mplWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.pathEdit = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathEdit.sizePolicy().hasHeightForWidth())
        self.pathEdit.setSizePolicy(sizePolicy)
        self.pathEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.pathEdit.setObjectName(_fromUtf8("pathEdit"))
        self.horizontalLayout.addWidget(self.pathEdit)
        self.pathBtn = QtGui.QToolButton(self.centralWidget)
        self.pathBtn.setObjectName(_fromUtf8("pathBtn"))
        self.horizontalLayout.addWidget(self.pathBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startBtn = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startBtn.sizePolicy().hasHeightForWidth())
        self.startBtn.setSizePolicy(sizePolicy)
        self.startBtn.setObjectName(_fromUtf8("startBtn"))
        self.horizontalLayout.addWidget(self.startBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.ftypeBox = QtGui.QComboBox(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ftypeBox.sizePolicy().hasHeightForWidth())
        self.ftypeBox.setSizePolicy(sizePolicy)
        self.ftypeBox.setMinimumSize(QtCore.QSize(100, 0))
        self.ftypeBox.setToolTip(_fromUtf8(""))
        self.ftypeBox.setEditable(False)
        self.ftypeBox.setFrame(True)
        self.ftypeBox.setObjectName(_fromUtf8("ftypeBox"))
        self.ftypeBox.addItem(_fromUtf8(""))
        self.ftypeBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.ftypeBox)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.fileoptsEdit = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileoptsEdit.sizePolicy().hasHeightForWidth())
        self.fileoptsEdit.setSizePolicy(sizePolicy)
        self.fileoptsEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.fileoptsEdit.setObjectName(_fromUtf8("fileoptsEdit"))
        self.horizontalLayout_2.addWidget(self.fileoptsEdit)
        spacerItem1 = QtGui.QSpacerItem(27, 23, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.mpl_hist = MplWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_hist.sizePolicy().hasHeightForWidth())
        self.mpl_hist.setSizePolicy(sizePolicy)
        self.mpl_hist.setMinimumSize(QtCore.QSize(0, 200))
        self.mpl_hist.setObjectName(_fromUtf8("mpl_hist"))
        self.verticalLayout.addWidget(self.mpl_hist)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.nextBtn = QtGui.QToolButton(self.centralWidget)
        self.nextBtn.setMinimumSize(QtCore.QSize(50, 0))
        self.nextBtn.setObjectName(_fromUtf8("nextBtn"))
        self.horizontalLayout_3.addWidget(self.nextBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        mplWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(mplWindow)
        QtCore.QMetaObject.connectSlotsByName(mplWindow)

    def retranslateUi(self, mplWindow):
        mplWindow.setWindowTitle(QtGui.QApplication.translate("mplWindow", "Trajectory Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mplWindow", "Data Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.pathBtn.setText(QtGui.QApplication.translate("mplWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.startBtn.setText(QtGui.QApplication.translate("mplWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mplWindow", "File Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.ftypeBox.setItemText(0, QtGui.QApplication.translate("mplWindow", "QDF", None, QtGui.QApplication.UnicodeUTF8))
        self.ftypeBox.setItemText(1, QtGui.QApplication.translate("mplWindow", "ABF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mplWindow", "File Read Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBtn.setText(QtGui.QApplication.translate("mplWindow", "-->", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
