#!/bin/sh

plat=`uname`

if [ $plat == 'Darwin' ]; then
        export FFLAGS="-ff2c"
fi


set -x

pip install numpy==1.8.1
pip install cython==0.20.1
pip install scipy==0.15.0
# pip install pyzmq==14.3.1
pip install matplotlib==1.3.1
pip install lmfit==0.7.4
pip install uncertainties==2.4.6
pip install PyWavelets==0.2.2
