#!/bin/sh

plat=`uname -s`

if [ $plat=='Darwin' ]; then
    mathbase=~/Library/Mathematica/Applications/
elif [ $plat=='Linux' ]; then
	mathbase = ~/.Mathematica/Applications/
fi

cp addons/mathematica/MosaicUtils.m ${mathbase}
cp addons/mathematica/MosaicAnalysis.m ${mathbase}
cp addons/mathematica/Util.m ${mathbase}

echo "Installed Mathematica addons in" $mathbase	

