#!/bin/sh

plat=`uname -s`

if [ $plat=='Darwin' ]; then
	ODBCAdminURL="http://supportdownload.apple.com/download.info.apple.com/Apple_Support_Area/Apple_Software_Updates/Mac_OS_X/downloads/018-4778.20090828.Prt65/ODBCAdministrator.dmg"
	SQLiteURL="http://www.ch-werner.de/sqliteodbc/sqlite3-odbc-0.93.dmg"

	# Alias SQL XOP
	mkdir -p "~/Documents/WaveMetrics/Igor Pro 6 User Files/Igor Extensions/"
	ln -s "/Applications/Igor Pro 6.3 Folder/More Extensions/Utilities/SQL.xop" $HOME"/Documents/WaveMetrics/Igor Pro 6 User Files/Igor Extensions/"

	volprefix="/Volumes/"
	volname=`diskutil info / | grep "Volume Name:" | awk -F "Volume Name:        " '{print $2}' | sed 's/^ *//'`
	
	# Install OS X ODBC Administrator
	curl -o ./ODBCAdministrator.dmg $ODBCAdminURL
	hdiutil mount ODBCAdministrator.dmg
	sudo installer -package "/Volumes/ODBC Administrator/ODBCAdministrator.pkg" -target "$volprefix$volname"
	hdiutil unmount "/Volumes/ODBC Administrator/"
	rm ./ODBCAdministrator.dmg


	# Install SQLite driver for ODBC
	curl -o ./sqlite3-odbc-0.93.dmg $SQLiteURL
	hdiutil mount sqlite3-odbc-0.93.dmg 
	sudo installer -package /Volumes/sqlite3-odbc-0.93/sqlite3odbc0.93.pkg -target "$volprefix$volname"
	hdiutil unmount /Volumes/sqlite3-odbc-0.93/
	rm ./sqlite3-odbc-0.93.dmg
	

	SQLCMD='myodbc-installer -d -a -n "SQLite3 Driver" -t "DRIVER=/usr/lib/libsqlite3odbc-0.93.dylib;SETUP=/usr/lib/libsqlite3odbc-0.93.dylib"'
	eval "$SQLCMD"
elif [ $plat=='Linux' ]; then
	echo "Platform not supported"
fi

echo "Installed IGOR addons"

