#!/bin/sh

# always run this script from the ustrade root directory

#set -x
source dependencies/.scripts/set-shell-vars-sh

cwd=${PWD}


cd dependencies/
tar xzf .tarballs/zeromq-2.2.0.tar.gz
cd zeromq-2.2.0

./configure --prefix $cwd/dependencies
make -j8
make install
cd ../../
rm -rf dependencies/zeromq-2.2.0
