#!/bin/sh

# always run this script from the ustrade root directory

#set -x
source dependencies/.scripts/set-shell-vars-sh

cwd=${PWD}


cd dependencies/
tar xzf .tarballs/nose-1.3.0.tar.gz
cd nose-1.3.0

python setup.py configure
python setup.py install --prefix=..

cd ../../
rm -rf dependencies/nose-1.3.0
