#!/bin/sh

# always run this script from the ustrade root directory

#set -x
source dependencies/.scripts/set-shell-vars-sh

cwd=${PWD}


cd dependencies/
tar xzf .tarballs/uncertainties-2.3.6.tar.gz
cd uncertainties-2.3.6

python setup.py configure
python setup.py install --prefix=..

cd ../../
rm -rf dependencies/uncertainties-2.3.6
