#!/bin/sh

# always run this script from the ustrade root directory

#set -x
source dependencies/.scripts/set-shell-vars-sh

cwd=${PWD}


cd dependencies/
tar xzf .tarballs/numpy-1.7.1.tar.gz
cd numpy-1.7.1

python setup.py configure
python setup.py install --prefix=..

cd ../../
rm -rf dependencies/numpy-1.7.1
