#!/bin/sh

# always run this script from the ustrade root directory

set -x
source dependencies/.scripts/set-shell-vars-sh

cwd=${PWD}


cd dependencies/

# Freetype
tar xzf .tarballs/freetype-2.4.7.tar.gz
cd freetype-2.4.7

./configure --prefix $cwd/dependencies
make -j8
make install

cd ../
rm -rf freetype-2.4.7

# LibPNG
tar xzf .tarballs/libpng-1.5.6.tar.gz
cd libpng-1.5.6

./configure --prefix $cwd/dependencies
make -j8
make install

cd ../
rm -rf libpng-1.5.6

# Finally Matplotlib
tar xzf .tarballs/matplotlib-1.2.1.tar.gz
cd matplotlib-1.2.1

if [ $plat == 'Linux' ]; then
	bash ../.scripts/setup-matplotlib-build-sh $cwd/dependencies False > setup.cfg
else
	bash ../.scripts/setup-matplotlib-build-sh $cwd/dependencies True > setup.cfg
fi
python setup.py build
python setup.py install --prefix=$cwd/dependencies

# all done
cd ../../
rm -rf dependencies/matplotlib-1.2.1
