#!/bin/sh

# always run this script from the ustrade root directory

set -x

cwd=${PWD}

export PATH=$cwd/dependencies/bin/:$PATH
export LD_LIBRARY_PATH=$cwd/dependencies/lib/:/usr/X11/lib/:$LD_LIBRARY_PATH

plat=`uname` 

if [ "${PYTHONPATH}" == "" ]; then
	pypath=""
else
	pypath=`echo $PYTHONPATH | grep -i $cwd/dependencies/lib/python2.7/site-packages`
fi

if [ "$pypath" == "" ]; then
	export PYTHONPATH=$cwd:$cwd/dependencies/lib/python2.7/site-packages:$PYTHONPATH
fi

set +x


